### ISSUE TITLE
Convention for vector describing a beam

### ISSUE THREAD

**Issue by KronosTheLate** [ngedwin98/ABCDBeamTrace.jl#11]
It should be explicit which convention this paclage uses for representing a beam. I personally have enountered 
[ distance from optical axis ; slope]
And the opposite order.

**Comment by ngedwin98** [comment]
Just remembered this issue while writing my reply in https://github.com/ngedwin98/ABCDBeamTrace.jl/issues/12#issuecomment-1716593348. Rather than simply using a 2D vector for a beam, this package tries to incorporate more semantic information using a `Beam` struct, which has both the ray information and the Gaussian beam information (as well as refractive index and wavelength). So in my notation, `distance from optical axis` is `x` (which I call distance from propagation ray along the transverse plane) and `slope` is `θ` (because in a paraxial approximation tan(_θ_) = _θ_). This is in the hopes of not needing to really touch the matrices in a future, properly designed interface.

**Comment by KronosTheLate** [comment]
That all sounds reasonable. Thanks!
